# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: TouringMachine
open_collective: # Replace with a single Open Collective username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.ascendlearning.org/support-us/', 'https://www.covenanthouse.org/donation-options/donate-today?origin=DHQEI2002EHI0NN&utm_source=1908evergreenweb&utm_medium=cpc&utm_campaign=FY20Evergreen&utm_content=bsd1908evergreenweb&gclid=EAIaIQobChMImI-QoZqo6QIVxtSzCh1-EQHYEAAYASAAEgKNZPD_BwE']
